// Generated by Wrangler on Fri Jun 21 2024 21:22:50 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	URLS_KV: KVNamespace;
}
