// Generated by Wrangler on Sat Jun 22 2024 15:46:24 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	URLS_KV: KVNamespace;
	AUTH_SECRET: string;
	AUTH_D1: D1Database;
}
