// import type { Metadata } from "next";
import {Inter} from "next/font/google";
import './global.css'
import Topbar from "@/components/toolbar";

const inter = Inter({subsets: ["latin"]});

export const runtime = 'edge'

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en" className="h-full">
        <body className={inter.className + " h-full flex flex-col"}>
        <Topbar/>
        {children}
        </body>
        </html>
    );
}
